This is cutadapt 4.1 with Python 3.10.6
Command line parameters: -g GTGYCAGCMGCCGCGGTAA -G GGACTACNVGGGTWTCTAAT -o trimmed/CBW_01_16S_S1_R1_trimmed.fastq -p trimmed/CBW_01_16S_S1_R2_trimmed.fastq /projects/ps-shurinlab/Yos_water_DNA/16S_Yos_data/CBW_01_16S_S1_L001_R1_001.fastq /projects/ps-shurinlab/Yos_water_DNA/16S_Yos_data/CBW_01_16S_S1_L001_R2_001.fastq
Traceback (most recent call last):
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/bin/cutadapt", line 8, in <module>
    sys.exit(main_cli())
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/__main__.py", line 1014, in main_cli
    main(sys.argv[1:])
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/__main__.py", line 1076, in main
    outfiles = open_output_files(
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/__main__.py", line 532, in open_output_files
    out, out2 = file_opener.xopen_pair(args.output, args.paired_output, "wb")
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 223, in xopen_pair
    file1 = self.xopen_or_none(path1, mode)
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 215, in xopen_or_none
    return self.xopen(path, mode)
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 205, in xopen
    f = open_raise_limit(
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 52, in open_raise_limit
    f = func(*args, **kwargs)
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/xopen/__init__.py", line 1119, in xopen
    opened_file = open(filename, mode, **text_mode_kwargs)
FileNotFoundError: [Errno 2] No such file or directory: 'trimmed/CBW_01_16S_S1_R1_trimmed.fastq'
This is cutadapt 4.1 with Python 3.10.6
Command line parameters: -g GTGYCAGCMGCCGCGGTAA -G GGACTACNVGGGTWTCTAAT -o trimmed/CBW_02_16S_S2_R1_trimmed.fastq -p trimmed/CBW_02_16S_S2_R2_trimmed.fastq /projects/ps-shurinlab/Yos_water_DNA/16S_Yos_data/CBW_02_16S_S2_L001_R1_001.fastq /projects/ps-shurinlab/Yos_water_DNA/16S_Yos_data/CBW_02_16S_S2_L001_R2_001.fastq
Traceback (most recent call last):
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/bin/cutadapt", line 8, in <module>
    sys.exit(main_cli())
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/__main__.py", line 1014, in main_cli
    main(sys.argv[1:])
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/__main__.py", line 1076, in main
    outfiles = open_output_files(
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/__main__.py", line 532, in open_output_files
    out, out2 = file_opener.xopen_pair(args.output, args.paired_output, "wb")
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 223, in xopen_pair
    file1 = self.xopen_or_none(path1, mode)
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 215, in xopen_or_none
    return self.xopen(path, mode)
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 205, in xopen
    f = open_raise_limit(
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 52, in open_raise_limit
    f = func(*args, **kwargs)
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/xopen/__init__.py", line 1119, in xopen
    opened_file = open(filename, mode, **text_mode_kwargs)
FileNotFoundError: [Errno 2] No such file or directory: 'trimmed/CBW_02_16S_S2_R1_trimmed.fastq'
This is cutadapt 4.1 with Python 3.10.6
Command line parameters: -g GTGYCAGCMGCCGCGGTAA -G GGACTACNVGGGTWTCTAAT -o trimmed/CBW_03_16S_S3_R1_trimmed.fastq -p trimmed/CBW_03_16S_S3_R2_trimmed.fastq /projects/ps-shurinlab/Yos_water_DNA/16S_Yos_data/CBW_03_16S_S3_L001_R1_001.fastq /projects/ps-shurinlab/Yos_water_DNA/16S_Yos_data/CBW_03_16S_S3_L001_R2_001.fastq
Traceback (most recent call last):
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/bin/cutadapt", line 8, in <module>
    sys.exit(main_cli())
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/__main__.py", line 1014, in main_cli
    main(sys.argv[1:])
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/__main__.py", line 1076, in main
    outfiles = open_output_files(
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/__main__.py", line 532, in open_output_files
    out, out2 = file_opener.xopen_pair(args.output, args.paired_output, "wb")
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 223, in xopen_pair
    file1 = self.xopen_or_none(path1, mode)
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 215, in xopen_or_none
    return self.xopen(path, mode)
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 205, in xopen
    f = open_raise_limit(
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 52, in open_raise_limit
    f = func(*args, **kwargs)
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/xopen/__init__.py", line 1119, in xopen
    opened_file = open(filename, mode, **text_mode_kwargs)
FileNotFoundError: [Errno 2] No such file or directory: 'trimmed/CBW_03_16S_S3_R1_trimmed.fastq'
This is cutadapt 4.1 with Python 3.10.6
Command line parameters: -g GTGYCAGCMGCCGCGGTAA -G GGACTACNVGGGTWTCTAAT -o trimmed/CBW_04_16S_S4_R1_trimmed.fastq -p trimmed/CBW_04_16S_S4_R2_trimmed.fastq /projects/ps-shurinlab/Yos_water_DNA/16S_Yos_data/CBW_04_16S_S4_L001_R1_001.fastq /projects/ps-shurinlab/Yos_water_DNA/16S_Yos_data/CBW_04_16S_S4_L001_R2_001.fastq
Traceback (most recent call last):
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/bin/cutadapt", line 8, in <module>
    sys.exit(main_cli())
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/__main__.py", line 1014, in main_cli
    main(sys.argv[1:])
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/__main__.py", line 1076, in main
    outfiles = open_output_files(
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/__main__.py", line 532, in open_output_files
    out, out2 = file_opener.xopen_pair(args.output, args.paired_output, "wb")
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 223, in xopen_pair
    file1 = self.xopen_or_none(path1, mode)
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 215, in xopen_or_none
    return self.xopen(path, mode)
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 205, in xopen
    f = open_raise_limit(
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 52, in open_raise_limit
    f = func(*args, **kwargs)
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/xopen/__init__.py", line 1119, in xopen
    opened_file = open(filename, mode, **text_mode_kwargs)
FileNotFoundError: [Errno 2] No such file or directory: 'trimmed/CBW_04_16S_S4_R1_trimmed.fastq'
This is cutadapt 4.1 with Python 3.10.6
Command line parameters: -g GTGYCAGCMGCCGCGGTAA -G GGACTACNVGGGTWTCTAAT -o trimmed/CBW_05_16S_S5_R1_trimmed.fastq -p trimmed/CBW_05_16S_S5_R2_trimmed.fastq /projects/ps-shurinlab/Yos_water_DNA/16S_Yos_data/CBW_05_16S_S5_L001_R1_001.fastq /projects/ps-shurinlab/Yos_water_DNA/16S_Yos_data/CBW_05_16S_S5_L001_R2_001.fastq
Traceback (most recent call last):
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/bin/cutadapt", line 8, in <module>
    sys.exit(main_cli())
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/__main__.py", line 1014, in main_cli
    main(sys.argv[1:])
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/__main__.py", line 1076, in main
    outfiles = open_output_files(
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/__main__.py", line 532, in open_output_files
    out, out2 = file_opener.xopen_pair(args.output, args.paired_output, "wb")
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 223, in xopen_pair
    file1 = self.xopen_or_none(path1, mode)
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 215, in xopen_or_none
    return self.xopen(path, mode)
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 205, in xopen
    f = open_raise_limit(
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 52, in open_raise_limit
    f = func(*args, **kwargs)
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/xopen/__init__.py", line 1119, in xopen
    opened_file = open(filename, mode, **text_mode_kwargs)
FileNotFoundError: [Errno 2] No such file or directory: 'trimmed/CBW_05_16S_S5_R1_trimmed.fastq'
This is cutadapt 4.1 with Python 3.10.6
Command line parameters: -g GTGYCAGCMGCCGCGGTAA -G GGACTACNVGGGTWTCTAAT -o trimmed/CBW_06_16S_S6_R1_trimmed.fastq -p trimmed/CBW_06_16S_S6_R2_trimmed.fastq /projects/ps-shurinlab/Yos_water_DNA/16S_Yos_data/CBW_06_16S_S6_L001_R1_001.fastq /projects/ps-shurinlab/Yos_water_DNA/16S_Yos_data/CBW_06_16S_S6_L001_R2_001.fastq
Traceback (most recent call last):
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/bin/cutadapt", line 8, in <module>
    sys.exit(main_cli())
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/__main__.py", line 1014, in main_cli
    main(sys.argv[1:])
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/__main__.py", line 1076, in main
    outfiles = open_output_files(
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/__main__.py", line 532, in open_output_files
    out, out2 = file_opener.xopen_pair(args.output, args.paired_output, "wb")
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 223, in xopen_pair
    file1 = self.xopen_or_none(path1, mode)
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 215, in xopen_or_none
    return self.xopen(path, mode)
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 205, in xopen
    f = open_raise_limit(
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 52, in open_raise_limit
    f = func(*args, **kwargs)
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/xopen/__init__.py", line 1119, in xopen
    opened_file = open(filename, mode, **text_mode_kwargs)
FileNotFoundError: [Errno 2] No such file or directory: 'trimmed/CBW_06_16S_S6_R1_trimmed.fastq'
This is cutadapt 4.1 with Python 3.10.6
Command line parameters: -g GTGYCAGCMGCCGCGGTAA -G GGACTACNVGGGTWTCTAAT -o trimmed/CBW_07_16S_S7_R1_trimmed.fastq -p trimmed/CBW_07_16S_S7_R2_trimmed.fastq /projects/ps-shurinlab/Yos_water_DNA/16S_Yos_data/CBW_07_16S_S7_L001_R1_001.fastq /projects/ps-shurinlab/Yos_water_DNA/16S_Yos_data/CBW_07_16S_S7_L001_R2_001.fastq
Traceback (most recent call last):
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/bin/cutadapt", line 8, in <module>
    sys.exit(main_cli())
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/__main__.py", line 1014, in main_cli
    main(sys.argv[1:])
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/__main__.py", line 1076, in main
    outfiles = open_output_files(
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/__main__.py", line 532, in open_output_files
    out, out2 = file_opener.xopen_pair(args.output, args.paired_output, "wb")
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 223, in xopen_pair
    file1 = self.xopen_or_none(path1, mode)
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 215, in xopen_or_none
    return self.xopen(path, mode)
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 205, in xopen
    f = open_raise_limit(
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 52, in open_raise_limit
    f = func(*args, **kwargs)
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/xopen/__init__.py", line 1119, in xopen
    opened_file = open(filename, mode, **text_mode_kwargs)
FileNotFoundError: [Errno 2] No such file or directory: 'trimmed/CBW_07_16S_S7_R1_trimmed.fastq'
This is cutadapt 4.1 with Python 3.10.6
Command line parameters: -g GTGYCAGCMGCCGCGGTAA -G GGACTACNVGGGTWTCTAAT -o trimmed/CBW_08_16S_S8_R1_trimmed.fastq -p trimmed/CBW_08_16S_S8_R2_trimmed.fastq /projects/ps-shurinlab/Yos_water_DNA/16S_Yos_data/CBW_08_16S_S8_L001_R1_001.fastq /projects/ps-shurinlab/Yos_water_DNA/16S_Yos_data/CBW_08_16S_S8_L001_R2_001.fastq
Traceback (most recent call last):
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/bin/cutadapt", line 8, in <module>
    sys.exit(main_cli())
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/__main__.py", line 1014, in main_cli
    main(sys.argv[1:])
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/__main__.py", line 1076, in main
    outfiles = open_output_files(
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/__main__.py", line 532, in open_output_files
    out, out2 = file_opener.xopen_pair(args.output, args.paired_output, "wb")
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 223, in xopen_pair
    file1 = self.xopen_or_none(path1, mode)
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 215, in xopen_or_none
    return self.xopen(path, mode)
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 205, in xopen
    f = open_raise_limit(
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 52, in open_raise_limit
    f = func(*args, **kwargs)
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/xopen/__init__.py", line 1119, in xopen
    opened_file = open(filename, mode, **text_mode_kwargs)
FileNotFoundError: [Errno 2] No such file or directory: 'trimmed/CBW_08_16S_S8_R1_trimmed.fastq'
This is cutadapt 4.1 with Python 3.10.6
Command line parameters: -g GTGYCAGCMGCCGCGGTAA -G GGACTACNVGGGTWTCTAAT -o trimmed/CBW_09_16S_S9_R1_trimmed.fastq -p trimmed/CBW_09_16S_S9_R2_trimmed.fastq /projects/ps-shurinlab/Yos_water_DNA/16S_Yos_data/CBW_09_16S_S9_L001_R1_001.fastq /projects/ps-shurinlab/Yos_water_DNA/16S_Yos_data/CBW_09_16S_S9_L001_R2_001.fastq
Traceback (most recent call last):
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/bin/cutadapt", line 8, in <module>
    sys.exit(main_cli())
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/__main__.py", line 1014, in main_cli
    main(sys.argv[1:])
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/__main__.py", line 1076, in main
    outfiles = open_output_files(
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/__main__.py", line 532, in open_output_files
    out, out2 = file_opener.xopen_pair(args.output, args.paired_output, "wb")
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 223, in xopen_pair
    file1 = self.xopen_or_none(path1, mode)
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 215, in xopen_or_none
    return self.xopen(path, mode)
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 205, in xopen
    f = open_raise_limit(
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 52, in open_raise_limit
    f = func(*args, **kwargs)
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/xopen/__init__.py", line 1119, in xopen
    opened_file = open(filename, mode, **text_mode_kwargs)
FileNotFoundError: [Errno 2] No such file or directory: 'trimmed/CBW_09_16S_S9_R1_trimmed.fastq'
This is cutadapt 4.1 with Python 3.10.6
Command line parameters: -g GTGYCAGCMGCCGCGGTAA -G GGACTACNVGGGTWTCTAAT -o trimmed/CBW_10_16S_S10_R1_trimmed.fastq -p trimmed/CBW_10_16S_S10_R2_trimmed.fastq /projects/ps-shurinlab/Yos_water_DNA/16S_Yos_data/CBW_10_16S_S10_L001_R1_001.fastq /projects/ps-shurinlab/Yos_water_DNA/16S_Yos_data/CBW_10_16S_S10_L001_R2_001.fastq
Traceback (most recent call last):
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/bin/cutadapt", line 8, in <module>
    sys.exit(main_cli())
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/__main__.py", line 1014, in main_cli
    main(sys.argv[1:])
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/__main__.py", line 1076, in main
    outfiles = open_output_files(
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/__main__.py", line 532, in open_output_files
    out, out2 = file_opener.xopen_pair(args.output, args.paired_output, "wb")
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 223, in xopen_pair
    file1 = self.xopen_or_none(path1, mode)
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 215, in xopen_or_none
    return self.xopen(path, mode)
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 205, in xopen
    f = open_raise_limit(
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/cutadapt/utils.py", line 52, in open_raise_limit
    f = func(*args, **kwargs)
  File "/Users/chriswall/opt/miniconda3/envs/cutadaptenv/lib/python3.10/site-packages/xopen/__init__.py", line 1119, in xopen
    opened_file = open(filename, mode, **text_mode_kwargs)
FileNotFoundError: [Errno 2] No such file or directory: 'trimmed/CBW_10_16S_S10_R1_trimmed.fastq'
bash: /data/CBW_01_16S_S1_L001_R1_001.fastq: No such file or directory
bash: /data/CBW_02_16S_S2_L001_R1_001.fastq: No such file or directory
bash: /data/CBW_03_16S_S3_L001_R1_001.fastq: No such file or directory
bash: /data/CBW_04_16S_S4_L001_R1_001.fastq: No such file or directory
bash: /data/CBW_05_16S_S5_L001_R1_001.fastq: No such file or directory
bash: /data/CBW_06_16S_S6_L001_R1_001.fastq: No such file or directory
bash: /data/CBW_07_16S_S7_L001_R1_001.fastq: No such file or directory
bash: /data/CBW_08_16S_S8_L001_R1_001.fastq: No such file or directory
bash: /data/CBW_09_16S_S9_L001_R1_001.fastq: No such file or directory
bash: /data/CBW_10_16S_S10_L001_R1_001.fastq: No such file or directory
